# mkdocs.yml
site_name: Made With ML
site_url: https://madewithml.com/
repo_url: https://github.com/GokuMohandas/mlops-course/
nav:
  - Home: index.md
  - workflows:
    - main: bnai/main.md
  - bnai:
    - data: bnai/data.md
    - evaluate: bnai/evaluate.md
    - predict: bnai/predict.md
    - train: bnai/train.md
    - utils: bnai/utils.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for any file changes
